# Generated by Django 5.2.1 on 2025-05-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='dR9qWkuKF1TNLUhb5no8PEc3RumEf1EM', editable=False, max_length=32, unique=True),
        ),
    ]
